apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: memcached
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - image: bitnami/memcached:latest
        name: memcached
      restartPolicy: Always

