apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: memcached
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: bitnami/memcached:latest
        name: memcached
        resources: {}
      restartPolicy: Always
status: {}

