apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: memcached
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: bitnami/memcached:latest
        name: memcached
        resources: {}
      restartPolicy: Always
status: {}

